# Build mdbook-plantuml release binary
Write-Host "Building mdbook-plantuml release binary..."
cargo build --release    

# Function to get a SHA256 hash of a file
function getFileHash {
    param (
        [string]$filePath
    )
    if (Test-Path $filePath) {
        $hash = Get-FileHash $filePath -Algorithm SHA256 | Select-Object -ExpandProperty Hash
        return $hash
    } else {
        Write-Error "File not found: $filePath"
        return $null
    }
}

# Cargo builds are not deterministic, so just taking teh has of the executable will result in a different GUID each time.
# Instead, we create a GUID based on Cargo.toml, Cargo.lock and the source files, so that the same source and version
# always results in the same GUID.
# WIX identifies different program versions by GUID (if I recall correctly), so this is important for upgrades to work correctly.
function createGuidBasedOnSources {
    # Get all files recursively, sort by path for determinism
    $files = Get-ChildItem -Path "../../src" -Recurse -File | Sort-Object FullName
    $concatenatedHashes = ""
    foreach ($file in $files) {
        $concatenatedHashes += getFileHash $file.FullName
    }

    # Include Cargo.toml and Cargo.lock hashes, these also affect the build output
    $concatenatedHashes += getFileHash "../../Cargo.toml"
    $concatenatedHashes += getFileHash "../../Cargo.lock"

    # Finally create a GUID from the concatenated hashes
    $guidBytes = [System.Text.Encoding]::UTF8.GetBytes($concatenatedHashes)
    $guidHash = [System.Security.Cryptography.SHA1]::Create().ComputeHash($guidBytes)
    $guid = [Guid]::New([byte[]]$guidHash[0..15])
    return $guid.ToString()
}

function generateVersionAndProjectFile {
    # Read version from Cargo.toml and write version.wxi for WiX
    $cargoTomlPath = "../../Cargo.toml"
    $wxiPath = "./version.wxi"
    
    # Read Cargo.toml and extract version, use the version to create version.wxi
    $cargoToml = Get-Content $cargoTomlPath -Raw
    if ($cargoToml -match 'version\s*=\s*"([^"]+)"') {
        $version = $matches[1]
        $guidStr = createGuidBasedOnSources
        
        $wxiContent = "<!-- generated by create_installer.ps1 -->`n<Include>`n  <?define MdbookPlantUMLVersion=$($version)?>`n  <?define MdbookPlantUMLGuid=$($guidStr)?>`n</Include>`n"
        Set-Content -Path $wxiPath -Value $wxiContent -Encoding UTF8

        Write-Host "version.wxi created with version $version and guid $guidStr"
    
        $wxprojPath = "mdbook-plantuml-v$($version).wixproj"
        Set-Content -Path $wxprojPath -Value "<Project Sdk=`"WixToolset.Sdk/6.0.0`" />" -Encoding UTF8
    } else {
        Write-Error "Could not find version in Cargo.toml"
    }
}

# Generate version.wxi
Write-Host "Generating version.wxi..."
generateVersionAndProjectFile

# And create the MSI installer
Write-Host "Creating MSI installer..."
dotnet build -c Release
