@startuml
participant Application
participant Preprocessor
participant markdown_plantuml_pipeline
participant CodeProcessor
participant Renderer
participant Backend

Application -> Application: main
	Application -> Application: handle_preprocessing
	Application -> Preprocessor: run
		Preprocessor -> Renderer: create renderer
		Renderer --> Preprocessor: renderer
		loop for each chapter
			Preprocessor -> markdown_plantuml_pipeline: render_plantuml_code_blocks(chapter markdown, renderer)
			markdown_plantuml_pipeline -> CodeProcessor: process
			loop for each PlantUML code block
				CodeProcessor -> Renderer: render
					Renderer -> Backend: render_from_string
				Renderer --> CodeProcessor: Markdown link to image
				CodeProcessor -> CodeProcessor: Replace PlantUML code block with link
			end				
			Renderer --> markdown_plantuml_pipeline: Patched chapter markdown
			markdown_plantuml_pipeline --> Preprocessor: Patched chapter markdown
			Preprocessor -> Preprocessor: Assign new chapter markdown
		end
@enduml