on:
  push:
    branches: [master]
  pull_request:

name: Continuous integration

jobs:
  build_and_test:
    name: "Build and test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [msrv, stable, beta, nightly, macos, windows]
        include:
          - build: msrv
            os: ubuntu-latest
            rust: "1.88.0"
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: nightly
            os: ubuntu-latest
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
    steps:
      - uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --all-features --release --verbose
      - run: cargo test --all-features --release --verbose

  clippy_and_fmt:
    name: "Clippy and format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update stable && rustup default stable
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --tests --examples
